#!/bin/bash
set -eo pipefail
[[ $TRACE ]] && set -x

if [[ -e /usr/share/debconf/confmodule ]]; then
  . /usr/share/debconf/confmodule
fi

case "$1" in
  install)
    db_get "clair/skip_key_file"
    if [ -z "${DEBCONF_RECONFIGURE}" ] && [ "$RET" != "true" ]; then
      db_get "clair/key_file"
      if [ ! -f "$RET" ]; then
        echo "Error: keyfile '$RET' not found." >&2
        echo "       To deploy, you will need to generate a keypair and add with 'clair ssh-keys:add'." >&2
        db_reset "clair/key_file"
      fi
    fi
    ;;

  upgrade) ;;

  abort-upgrade) ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
